<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>AppSettings</name>
    <message>
        <location filename="../../src/appsettings.cpp" line="71"/>
        <source>Unable to create autorun file from &apos;%1&apos;</source>
        <translation>无法在&apos;%1&apos;中创建自动启动文件</translation>
    </message>
</context>
<context>
    <name>OptimusManager</name>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="51"/>
        <location filename="../../src/optimusmanager.cpp" line="193"/>
        <source>Switch to Intel</source>
        <translation>切换到 Intel</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="52"/>
        <location filename="../../src/optimusmanager.cpp" line="194"/>
        <source>Switch to Nvidia</source>
        <translation>切换到 Nvidia</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="54"/>
        <location filename="../../src/optimusmanager.cpp" line="195"/>
        <source>Exit</source>
        <translation>退出</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="62"/>
        <location filename="../../src/optimusmanager.cpp" line="190"/>
        <source>Current videocard: </source>
        <translation>目前使用的显卡：</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="171"/>
        <location filename="../../src/optimusmanager.cpp" line="181"/>
        <source>The specified icon &apos;%1&apos; for the current GPU is invalid. The default icon will be used.</source>
        <translation>为当前使用的 GPU 指定的图标 %1 无效。将使用默认图标。</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="208"/>
        <source>You are about to switch GPU.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="210"/>
        <source>You will be automatically logged out to apply the changes.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="221"/>
        <source>The Optimus Manager service is not running.</source>
        <translation type="unfinished"></translation>
    </message>
    <message numerus="yes">
        <location filename="../../src/optimusmanager.cpp" line="273"/>
        <source>There are %n other(s) desktop sessions open.</source>
        <translation type="unfinished">
            <numerusform></numerusform>
        </translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="273"/>
        <source>The GPU switch will not become effective until you have manually logged out from ALL desktop sessions.
Continue?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="287"/>
        <source>Wayland session found.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="288"/>
        <source>Session %1, started by %2, is a Wayland session. Wayland is not supported by Optimus Manager, so GPU switching may fail.
Continue anyway?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="306"/>
        <source>The Bumblebee service (%1) is running.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="347"/>
        <source>The Xorg driver &apos;%1&apos; is not installed.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="348"/>
        <source>Optimus Manager will use &apos;%1&apos; driver instead. You can change driver in settings or install the &apos;%2&apos; driver from the package &apos;%3&apos;.
Continue anyway?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="365"/>
        <source>Unable to connect to Optimus Manager daemon to switch GPU: %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="321"/>
        <source>If you did not create it yourself, it was likely generated by your distribution or by an Nvidia utility.
This file may contain hard-coded GPU configuration that could interfere with Optimus Manager, so it is recommended that you delete it before proceeding.
Ignore this warning and proceed with GPU switching?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="335"/>
        <source>This file was auto-generated by the Manjaro driver utility (MHWD). This will likely interfere with GPU switching, so Optimus Manager will delete this file automatically if you proceded with GPU switching.
Proceed?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="212"/>
        <source>After applying the settings, you will need to manually re-login to change the video card.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="222"/>
        <source>Please enable and start it with:
&apos;%1&apos;
&apos;%2&apos;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="233"/>
        <location filename="../../src/optimusmanager.cpp" line="247"/>
        <source>The %1 module does not seem to be available for the current kernel.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="234"/>
        <source>Power switching will not work.
You can set &apos;%1&apos; for GPU switching in settings or install bbswitch forthe default kernel with &apos;%2&apos; or for all kernels with &apos;%3&apos;.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="248"/>
        <source>It is likely the Nvidia driver was not properly installed. GPU switching will probably fail, continue anyway?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="258"/>
        <source>Looks like you&apos;re using a non-patched version of the Gnome Display Manager (GDM).</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="259"/>
        <source>GDM need to be patched for Prime switching. Follow &lt;a href=&apos;https://github.com/Askannz/optimus-manager&apos;&gt;this&lt;/a&gt; instructions to install a patched version. Without a patched GDM version, GPU switching will likely fail.
Continue anyway?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="272"/>
        <source>Multiple running sessions detected.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="307"/>
        <source>This can interfere with Optimus Manager. Before attempting a GPU switch, it is recommended that you disable this service with &apos;%1&apos; and reboot your computer.
Ignore this warning and proceed with GPU switching now?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="320"/>
        <location filename="../../src/optimusmanager.cpp" line="334"/>
        <source>Found a Xorg config file at &apos;%1&apos;.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="374"/>
        <source>Unable to send GPU name to switch to Optimus Manager daemon: %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="381"/>
        <source>Configuration successfully applied. Your GPU will be switched after next login.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>OptimusSettings</name>
    <message>
        <location filename="../../src/optimussettings.cpp" line="64"/>
        <source>Unable to connect to optimus-manager daemon to send startup mode: </source>
        <translation>无法连接到 optimus-manager 后台以发送启动模式：</translation>
    </message>
    <message>
        <location filename="../../src/optimussettings.cpp" line="70"/>
        <source>Unable to send startup mode to optimus-manager daemon: </source>
        <translation>无法发送启动模式到 optimus-manager-daemon 后台：</translation>
    </message>
    <message>
        <location filename="../../src/optimussettings.cpp" line="79"/>
        <source>Unable to open startup mode file</source>
        <translation>无法打开启动模式文件</translation>
    </message>
    <message>
        <location filename="../../src/optimussettings.cpp" line="97"/>
        <source>Unknown mode in startup file</source>
        <translation>启动文件中存在未知模式</translation>
    </message>
</context>
<context>
    <name>SettingsDialog</name>
    <message>
        <location filename="../../src/settingsdialog.ui" line="14"/>
        <location filename="../../src/optimusmanager.cpp" line="49"/>
        <location filename="../../src/optimusmanager.cpp" line="192"/>
        <source>Settings</source>
        <translation>设置</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="59"/>
        <location filename="../../src/settingsdialog.ui" line="112"/>
        <source>General</source>
        <translation>常规</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="95"/>
        <source>About</source>
        <translation>关于</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="172"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Application language&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;应用程序语言&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="175"/>
        <source>Language:</source>
        <translation>语言：</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="122"/>
        <source>&lt;System language&gt;</source>
        <translation>&lt;系统语言&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="195"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;~/.config/autostart will be used&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;将会使用 ~/.config/autostart&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="198"/>
        <source>Launch at startup</source>
        <translation>系统启动时启动</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="205"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Show confirmation dialog when switching GPU&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;切换 GPU 时显示确认对话框&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="208"/>
        <source>Confirm switching</source>
        <translatorcomment>意译</translatorcomment>
        <translation>切换时确认</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="218"/>
        <source>Tray icons</source>
        <translation>托盘图标</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="224"/>
        <source>Intel icon:</source>
        <translation>Intel 图标：</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="245"/>
        <source>Nvidia icon:</source>
        <translation>Nvidia 图标：</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="252"/>
        <location filename="../../src/settingsdialog.ui" line="259"/>
        <source>Choose icon</source>
        <translation>选择图标</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="327"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Specify which GPU will be used by default when the system boots&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;指定系统启动时使用的 GPU&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="330"/>
        <source>Startup mode:</source>
        <translation>启动模式：</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="359"/>
        <source>Nvidia (one boot)</source>
        <translation>Nvidia（仅一次）</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="371"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Automatically log out the current desktop session when switching GPUs&lt;/p&gt;&lt;p&gt;At the moment this is only supported for Gnome, KDE Plasma and Xfce&lt;/p&gt;&lt;p&gt;If this options is disabled or you use a different desktop environment, GPU switching only becomes effective at the next graphical session login&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="374"/>
        <source>Automatic logout</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="381"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Module used for power switching&lt;/p&gt;&lt;p&gt;If you select &amp;quot;None&amp;quot;, no power switching will be done at all (the Nvidia GPU will stay powered at all times)&lt;/p&gt;&lt;p&gt;If you use bbswitch, you will not be able to use video outputs attached to your Nvidia GPU in Intel mode&lt;/p&gt;&lt;p&gt;To use the bbswitch mode, the bbswitch module must be installed for your current kernel&lt;/p&gt;&lt;p&gt;You can install it for the default kernel with &amp;quot;pacman -S bbswitch&amp;quot;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;功耗切换时使用的模块&lt;/p&gt;&lt;p&gt;如果您选择&amp;quot;无&amp;quot;则不会进行任何的功耗切换（Nvidia 显卡会一直保持启动）&lt;/p&gt;&lt;p&gt;如果您使用 bbswitch，则在 Intel 模式下，您将无法使用连接到 Nvidia GPU 的视频输出&lt;/p&gt;&lt;p&gt;若要使用 bbswitch 模式，您必须为当前内核安装 bbswitch 模块&lt;/p&gt;&lt;p&gt;您可以使用&amp;quot;pacman -S bbswitch&amp;quot;为默认内核安装 bbswitch 模块&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="384"/>
        <source>Switching backend:</source>
        <translation>切换后端：</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="296"/>
        <source>None</source>
        <translation>无</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="118"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Interface language&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="231"/>
        <location filename="../../src/settingsdialog.ui" line="238"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Path to the icon or icon name from theme&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="292"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Backend to be used for switching GPU&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="337"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;GPU that will be used during normal system startup&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="417"/>
        <source>Driver:</source>
        <translation>驱动：</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="507"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Enable AccelMethod option in the Xorg configuration&lt;br/&gt;&lt;br/&gt;This option compatible only with the Intel driver and will be ignored if it is not selected&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;在 Xorg 配置中启用 AccelMethod 选项&lt;br/&gt;&lt;br/&gt;仅与 Intel 驱动兼容，并且在不使用 Intel 驱动时自动忽略该选项&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="458"/>
        <source>Acceleration method:</source>
        <translation>加速方式：</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="479"/>
        <location filename="../../src/settingsdialog.ui" line="511"/>
        <source>Default</source>
        <translation>默认</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="475"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Enable TearFree option in the Xorg configuration&lt;br/&gt;&lt;br/&gt;This option compatible only with the Intel driver and will be ignored if it is not selected&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;在 Xorg 配置中启用 TearFree 选项&lt;br/&gt;&lt;br/&gt;仅与 Intel 驱动兼容，并且在不使用 Intel 驱动时自动忽略该选项&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="441"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Driver to use for the Intel GPU&lt;br/&gt;&lt;br/&gt;To use the intel driver, you need to install the package &amp;quot;xf86-video-intel&amp;quot;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="484"/>
        <source>Yes</source>
        <translation>是</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="489"/>
        <source>No</source>
        <translation>否</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="424"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;DRI version&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;DRI 版本&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="542"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Whether or not to enable modesetting for the nouveau driver&lt;/p&gt;&lt;p&gt;Does not affect modesetting for the Intel GPU driver&lt;/p&gt;&lt;p&gt;This option is incompatible with bbswitch and will be ignored if it is enabled&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;是否为 nouveau 驱动启用 modesetting&lt;/p&gt;&lt;p&gt;不会影响 Intel GPU 的 modesetting&lt;/p&gt;&lt;p&gt;该选项与 bbswitch 不兼容，并且 bbswitch 模式启用时会自动忽略该选项&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="585"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;This will be set using the Xsetup script passed to your login manager&lt;br/&gt;It will run the command&lt;/p&gt;&lt;p&gt;xrandr --dpi &amp;lt;dpi value&amp;gt;&lt;/p&gt;&lt;p&gt;Leave 0 for the default&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;这将使用会传给您的登录管理器的 Xsetup 脚本&lt;br/&gt;它会运行如下命令：&lt;/p&gt;&lt;p&gt;xrandr --dpi &amp;lt;dpi value&amp;gt;&lt;/p&gt;&lt;p&gt;填 0 则表示使用默认值&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="608"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Whether or not to enable modesetting&lt;/p&gt;&lt;p&gt;Required for PRIME Synchronization&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;是否启用 modesetting&lt;/p&gt;&lt;p&gt;PRIME Synchronization 要求启用该选项&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="618"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Whether or not to enable the NVreg_UsePageAttributeTable option in the Nvidia driver &lt;span style=&quot; font-style:italic;&quot;&gt;Recommended&lt;/span&gt;, can cause poor CPU performance otherwise&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;时是否在 Nvidia 驱动中启用 NVreg_UsePageAttributeTable 选项。&lt;span style=&quot; font-style:italic;&quot;&gt;建议开启&lt;/span&gt;，否则可能会造成 CPU 性能下降&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="628"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Enable CoolBits in the Xorg configuration and unlock clocking options in the Nvidia control panel&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;在 Xorg 配置中启用 CoolBits，并且解锁 Nvidia 设置中的 clocking 选项&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="631"/>
        <source>Overclocking options</source>
        <translation>超频选项</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="638"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Enable triple buffering&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;启用三倍缓存&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="641"/>
        <source>Triple buffer</source>
        <translation>三倍缓存</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="698"/>
        <location filename="../../src/settingsdialog.ui" line="829"/>
        <source>Version:</source>
        <translation>版本：</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="712"/>
        <location filename="../../src/settingsdialog.ui" line="806"/>
        <source>Autor:</source>
        <translation>作者：</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="719"/>
        <location filename="../../src/settingsdialog.ui" line="843"/>
        <source>License:</source>
        <translation>许可证：</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.cpp" line="206"/>
        <source>Select icon</source>
        <translation>选择图标</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.cpp" line="207"/>
        <source>Images (*.png *.jpg *.bmp);;All files(*)</source>
        <translation></translation>
    </message>
</context>
</TS>
