<?xml version="1.0" ?><!DOCTYPE TS><TS language="fi" version="2.1">
<context>
    <name>AppSettings</name>
    <message>
        <location filename="../../src/appsettings.cpp" line="76"/>
        <source>Unable to create autorun file from &apos;%1&apos;</source>
        <translation>Autorun-tiedostoa ei voi luoda osoitteesta &apos;%1&apos;</translation>
    </message>
</context>
<context>
    <name>OptimusManager</name>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="54"/>
        <location filename="../../src/optimusmanager.cpp" line="173"/>
        <source>Switch to Intel</source>
        <translation>Vaihda Inteliin</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="55"/>
        <location filename="../../src/optimusmanager.cpp" line="174"/>
        <source>Switch to Nvidia</source>
        <translation>Vaihda Nvidiaan</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="57"/>
        <location filename="../../src/optimusmanager.cpp" line="175"/>
        <source>Exit</source>
        <translation>Poistu</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="151"/>
        <location filename="../../src/optimusmanager.cpp" line="161"/>
        <source>The specified icon &apos;%1&apos; for the current GPU is invalid. The default icon will be used.</source>
        <translation>Määritetty GPU kuvake &apos;%1&apos; on virheellinen. Oletuskuvaketta käytetään.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="188"/>
        <source>You are about to switch GPU.</source>
        <translation>Olet vaihtamassa GPU:ta.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="190"/>
        <source>You will be automatically logged out to apply the changes.</source>
        <translation>Kirjaudut automaattisesti ulos ja muutokset tehdään.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="201"/>
        <source>The Optimus Manager service is not running.</source>
        <translation>Optimus Manager -palvelu ei ole käynnissä.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="250"/>
        <source>There are %1 other desktop sessions open. The GPU switch will not become effective until you have manually logged out from ALL desktop sessions.
Continue?</source>
        <translation>Muita työpöydän istuntoja on %1. GPU-kytkentä ei tule voimaan, ennen kuin olet kirjautunut ulos manuaalisesti kaikista työpöydän istunnoista.
Jatka?</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="264"/>
        <source>Wayland session found.</source>
        <translation>Wayland-istunto löytyi.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="265"/>
        <source>Session %1, started by %2, is a Wayland session. Wayland is not supported by Optimus Manager, so GPU switching may fail.
Continue anyway?</source>
        <translation>Istunto %1, jonka käynnisti %2, on Wayland-istunto. Optimus Manager ei tue Waylandia, joten GPU:n vaihto voi epäonnistua.
Jatka joka tapauksessa?</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="282"/>
        <source>The Bumblebee service (%1) is running.</source>
        <translation>Bumblebee-palvelu (%1) on käynnissä.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="325"/>
        <source>The Xorg driver &apos;%1&apos; is not installed.</source>
        <translation>Xorg-ajuria &apos;%1&apos; ei ole asennettu.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="326"/>
        <source>Optimus Manager will use '%1' driver instead. You can change driver in settings or install the '%2' driver from the package '%3'.
Continue anyway?</source>
        <translation>Optimus Manager käyttää sen sijaan &apos;%1&apos; -ohjainta. Voit muuttaa ohjaimen asetuksissa tai asentaa &apos;%2&apos; -ohjaimen paketista &apos;%3&apos;.
Jatka joka tapauksessa?</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="341"/>
        <source>Unable to connect to Optimus Manager daemon to switch GPU: %1</source>
        <translation>Optimus Manager -taustaprosessiin ei voi muodostaa yhteyttä GPU:n vaihtamiseksi: %1</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="297"/>
        <source>If you did not create it yourself, it was likely generated by your distribution or by an Nvidia utility.
This file may contain hard-coded GPU configuration that could interfere with Optimus Manager, so it is recommended that you delete it before proceeding.
Ignore this warning and proceed with GPU switching?</source>
        <translation>Jos et luonut sitä itse, se on todennäköisesti tehty järjestelmääsi tai Nvidia-apuohjelman avulla.
Tämä tiedosto voi sisältää laitetason GPU-kokoonpanon, joka saattaa häiritä Optimus Manageria, joten on suositeltavaa poistaa se ennen jatkamista.
Ohita tämä varoitus ja jatka GPU:n vaihtoa?</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="311"/>
        <source>This file was auto-generated by the Manjaro driver utility (MHWD). This will likely interfere with GPU switching, so Optimus Manager will delete this file automatically if you proceded with GPU switching.
Proceed?</source>
        <translation>Tämä tiedosto luotiin automaattisesti Manjaro ajuri-apuohjelmalla (MHWD). Tämä häiritsee todennäköisesti GPU:n vaihtoa, joten Optimus Manager poistaa tämän tiedoston automaattisesti, jos jatkat.
Jatketaanko?</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="192"/>
        <source>After applying the settings, you will need to manually re-login to change the video card.</source>
        <translation>Kun olet asentanut asetukset, sinun täytyy kirjautua uudelleen manuaalisesti vaihtaaksesi videokortin.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="65"/>
        <location filename="../../src/optimusmanager.cpp" line="170"/>
        <source>Current videocard: %1</source>
        <translation>Nykyinen videokortti: %1</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="202"/>
        <source>Please enable and start it with:
'%1'
&apos;%2&apos;</source>
        <translation>Ota käyttöön ja käynnistä se seuraavasti:
&apos;%1&apos;
&apos;%2&apos;</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="212"/>
        <location filename="../../src/optimusmanager.cpp" line="224"/>
        <source>The %1 module does not seem to be available for the current kernel.</source>
        <translation>%1 moduuli ei näytä olevan käytettävissä nykyiselle ytimelle.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="213"/>
        <source>Power switching will not work.
You can set &apos;%1&apos; for GPU switching in settings or install bbswitch forthe default kernel with &apos;%2&apos; or for all kernels with &apos;%3&apos;.</source>
        <translation>Virran katkaisu ei toimi.
Voit asettaa &apos;%1&apos; GPU-kytkimille asetuksissa tai asentaa bbswitch-oletus ytimen, jossa on &apos;%2&apos;, tai kaikille ytimille, joilla on &apos;%3&apos;.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="225"/>
        <source>It is likely the Nvidia driver was not properly installed. GPU switching will probably fail, continue anyway?</source>
        <translation>On todennäköistä, että Nvidia-ohjainta ei ole asennettu oikein. GPU-kytkentä todennäköisesti epäonnistuu, jatka silti?</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="235"/>
        <source>Looks like you&apos;re using a non-patched version of the Gnome Display Manager (GDM).</source>
        <translation>Näyttää siltä, että käytät Gnome Display Managerin (GDM) ei-korjattua versiota.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="236"/>
        <source>GDM need to be patched for Prime switching. Follow &lt;a href='https://github.com/Askannz/optimus-manager'&gt;this&lt;/a&gt; instructions to install a patched version. Without a patched GDM version, GPU switching will likely fail.
Continue anyway?</source>
        <translation>GDM on korjattava, jotta se voidaan vaihtaa. Asenna korjattu versio noudattamalla &lt;a href=&apos;https://github.com/Askannz/optimus-manager&apos;&gt;näitä &lt;/a&gt;ohjeita. Ilman korjattua GDM-versiota GPU-kytkentä todennäköisesti epäonnistuu.
Jatka joka tapauksessa?</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="249"/>
        <source>Multiple running sessions detected.</source>
        <translation>Useita käynnissä olevia istuntoja havaittiin.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="283"/>
        <source>This can interfere with Optimus Manager. Before attempting a GPU switch, it is recommended that you disable this service with '%1' and reboot your computer.
Ignore this warning and proceed with GPU switching now?</source>
        <translation>Tämä voi häiritä Optimus Manageria. Ennen kuin yrität GPU kytkentää, on suositeltavaa, että poistat tämän palvelun käytöstä painikkeella &apos;%1&apos; ja käynnistät tietokoneen uudelleen.
Ohita tämä varoitus ja jatka GPU:n vaihtamista nyt?</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="296"/>
        <location filename="../../src/optimusmanager.cpp" line="310"/>
        <source>Found a Xorg config file at &apos;%1&apos;.</source>
        <translation>Löytyi Xorg config-tiedosto &apos;%1&apos;.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="350"/>
        <source>Unable to send GPU name to switch to Optimus Manager daemon: %1</source>
        <translation>GPU-nimeä ei voi vaihtaa Optimus Manager -taustaprosessiin: %1</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="357"/>
        <source>Configuration successfully applied. Your GPU will be switched after next login.</source>
        <translation>Konfigurointi onnistui. GPU kytketään seuraavan kirjautumisen jälkeen.</translation>
    </message>
</context>
<context>
    <name>OptimusSettings</name>
    <message>
        <location filename="../../src/optimussettings.cpp" line="83"/>
        <source>Unable to connect to optimus-manager daemon to send startup mode: %1</source>
        <translation>Ei voi muodostaa yhteyttä Optimus-Manager taustaprosessiin. Lähettä käynnistystila seuraavasti: %1</translation>
    </message>
    <message>
        <location filename="../../src/optimussettings.cpp" line="91"/>
        <source>Unable to send startup mode to optimus-manager daemon: %1</source>
        <translation>Käynnistystilaa ei voi lähettää Optimus-Manager taustaprosessiin: %1</translation>
    </message>
    <message>
        <location filename="../../src/optimussettings.cpp" line="101"/>
        <source>Unable to open startup mode file</source>
        <translation>Käynnistystilan tiedoston avaaminen ei onnistu</translation>
    </message>
</context>
<context>
    <name>SettingsDialog</name>
    <message>
        <location filename="../../src/settingsdialog.ui" line="14"/>
        <location filename="../../src/optimusmanager.cpp" line="52"/>
        <location filename="../../src/optimusmanager.cpp" line="172"/>
        <source>Settings</source>
        <translation>Asetukset</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="59"/>
        <location filename="../../src/settingsdialog.ui" line="109"/>
        <source>General</source>
        <translation>Yleinen</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="95"/>
        <source>About</source>
        <translation>Tietoja</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="205"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Application language&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Sovelluksen kieli&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="208"/>
        <source>Language:</source>
        <translation>Kieli:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="119"/>
        <source>&lt;System language&gt;</source>
        <translation>&lt;System language&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="231"/>
        <source>Launch at startup</source>
        <translation>Käynnistä käynnistyksen yhteydessä</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="238"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Show confirmation dialog when switching GPU&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Näytä vahvistusikkuna, kun vaihdat GPU:n&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="241"/>
        <source>Confirm switching</source>
        <translation>Vahvista vaihtaminen</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="278"/>
        <source>Nvidia icon:</source>
        <translation>Nvidian kuvake:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="257"/>
        <source>Intel icon:</source>
        <translation>Intelin kuvake:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="325"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Specify which GPU will be used by default when the system boots&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Määritä, mitä GPU:ta käytetään oletuksena, kun järjestelmä käynnistyy&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="335"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Method to power switch the Nvidia card&lt;/p&gt;&lt;p&gt;&lt;span style=&quot; font-style:italic;&quot;&gt;None&lt;/span&gt;: do not use an external module for power management (for some laptop models it&apos;s preferable to use this option in combination with PCI power control)&lt;/p&gt;&lt;p&gt;&lt;span style=&quot; font-style:italic;&quot;&gt;Nouveau&lt;/span&gt;: load the nouveau module on the Nvidia card&lt;/p&gt;&lt;p&gt;&lt;span style=&quot; font-style:italic;&quot;&gt;Bbswitch&lt;/span&gt;: power off the card using the bbswitch module (requires the &amp;quot;bbswitch&amp;quot;dependency)&lt;/p&gt;&lt;p&gt;&lt;span style=&quot; font-style:italic;&quot;&gt;ACPI call&lt;/span&gt;: try various ACPI method calls to power the card on and off (requires the &amp;quot;acpi_call&amp;quot; dependency)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Tavat kytkeä virta Nvidia-korteille&lt;/p&gt;&lt;p&gt;&lt;span style=&quot; font-style:italic;&quot;&gt;Ei mitään&lt;/span&gt;: Älä käytä ulkoista moduulia virranhallintaan (joissakin kannettavissa malleissa on parempi käyttää tätä vaihtoehtoa yhdessä PCI-tehonohjauksen kanssa)&lt;/p&gt;&lt;p&gt;&lt;span style=&quot; font-style:italic;&quot;&gt;Nouveau&lt;/span&gt;: lataa nouveau moduli Nvidia kortille&lt;/p&gt;&lt;p&gt;&lt;span style=&quot; font-style:italic;&quot;&gt;Bbswitch&lt;/span&gt;:sammuta kortti bbswitch-modulin avulla (vaatii &quot;bbswitch&quot; riippuvuuden)&lt;/p&gt;&lt;p&gt;&lt;span style=&quot; font-style:italic;&quot;&gt;ACPI kutsu&lt;/span&gt;: Kokeile erilaisia ACPI-menetelmän kutsuja korttille. Vita päälle ja pois (vaatii &quot;acpi_call&quot; riippuvuuden) &lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="354"/>
        <source>ACPI call</source>
        <translation>ACPI kutsu</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="410"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Module used for power switching&lt;/p&gt;&lt;p&gt;If you select &amp;quot;None&amp;quot;, no power switching will be done at all (the Nvidia GPU will stay powered at all times)&lt;/p&gt;&lt;p&gt;If you use bbswitch, you will not be able to use video outputs attached to your Nvidia GPU in Intel mode&lt;/p&gt;&lt;p&gt;To use the bbswitch mode, the bbswitch module must be installed for your current kernel&lt;/p&gt;&lt;p&gt;You can install it for the default kernel with &amp;quot;pacman -S bbswitch&amp;quot;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Moduuli, jota käytetään vaihtoon&lt;/p&gt;&lt;p&gt;Jos valitset &quot;ei mitään&quot; &amp;quot;None&amp;quot, katkaisinta ei tehdä ollenkaan (NVIDIA GPU on aina päällä).&lt;/p&gt;&lt;p&gt;Jos käytät bbswitch-toimintoa, et voi käyttää Nvidia GPU -laitteeseen liitettyjä videolähtöjä Intel-tilassa&lt;/p&gt;&lt;p&gt;Bbswitch-tilan käyttämiseksi bbswitch-moduuli on asennettava nykyiselle ytimellesi&lt;/p&gt;&lt;p&gt;Voit asentaa sen ytimeen &amp;quot;pacman -S bbswitch&amp;quot;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="420"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Automatically log out the current desktop session when switching GPUs&lt;/p&gt;&lt;p&gt;This feature is currently supported for Gnome, KDE Plasma, Deepin, Xfce, i3, Sway, Openbox and AwesomeWM&lt;/p&gt;&lt;p&gt;If this options is disabled or you use a different desktop environment, GPU switching only becomes effective at the next graphical session login&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Kirjaudut ulos työpöydän istunnosta automaattisesti, kun vaihdat GPUta&lt;/p&gt;&lt;p&gt;Tällä hetkellä sitä tukee Gnome, KDE Plasma, Deepin, Xfce, i3, Sway, Openbox ja AwesomeWM.&lt;/p&gt;&lt;p&gt;Jos tämä asetus on poistettu käytöstä tai käytät eri työpöytäympäristöä, GPU vaihto tulee voimaan vasta seuraavassa graafisessa istunnossa&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="423"/>
        <source>Automatic logout</source>
        <translation>Automaattinen uloskirjautuminen</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="620"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Whether or not to enable modesetting for the nouveau driver&lt;/p&gt;&lt;p&gt;Does not affect modesetting for the Intel GPU driver&lt;/p&gt;&lt;p&gt;This option is incompatible with Bbswitch and will be ignored if it is enabled&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Sallitaanko nouveau tilojen käyttöönotto vai ei&lt;/p&gt;&lt;p&gt;Ei vaikutusta Intel GPU -ohjaimen tilaan&lt;/p&gt;&lt;p&gt;Tämä vaihtoehto ei ole yhteensopiva bbswitchin kanssa, ja se jätetään huomiotta, jos se on käytössä&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="663"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;This will be set using the Xsetup script passed to your login manager&lt;br/&gt;It will run the command&lt;/p&gt;&lt;p&gt;xrandr --dpi &amp;lt;dpi value&amp;gt;&lt;/p&gt;&lt;p&gt;Leave 0 for the default&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Tämä asetetaan Xsetup-sktiptin avulla kirjautumishallintaan&lt;br/&gt;Se suorittaa komennon&lt;/p&gt;&lt;p&gt;xrandr --dpi &amp;lt;dpi value&amp;gt;&lt;/p&gt;&lt;p&gt;Jätä oletusarvoksi 0&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="696"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Whether or not to enable the NVreg_UsePageAttributeTable option in the Nvidia driver &lt;span style=&quot; font-style:italic;&quot;&gt;Recommended&lt;/span&gt;, can cause poor CPU performance otherwise&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Otetaanko NVreg_UsePageAttributeTable vaihtoehto käyttöön Nvidia-ohjaimessa vai ei&lt;span style=&quot; font-style:italic;&quot;&gt;Suositus&lt;/span&gt;, voi muuten heikentää CPU suorittimen suorituskykyä</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="706"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Enable CoolBits in the Xorg configuration, which unlocks clocking options&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Ota CoolBits käyttöön Xorg-kokoonpanossa, joka avaa kellotusasetukset&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="709"/>
        <source>Overclocking options</source>
        <translation>Ylikellotuksen asetukset</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="228"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;~/.config/autostart will be used&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;~/.config/autostart käytetään&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="251"/>
        <source>Tray icons</source>
        <translation>Valikon kuvakkeet</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="285"/>
        <location filename="../../src/settingsdialog.ui" line="292"/>
        <source>Choose icon</source>
        <translation>Valitse kuvake</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="328"/>
        <source>Startup mode:</source>
        <translation>Käynnistystila:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="339"/>
        <source>None</source>
        <translation>Mitään</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="115"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Interface language&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Käyttöliittymän kieli&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="264"/>
        <location filename="../../src/settingsdialog.ui" line="271"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Path to the icon or icon name from theme&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Teeman kuvakkeen tai kuvakkeen nimen polku&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="385"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;GPU that will be used during normal system startup&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;GPU, jota käytetään normaalisti käynnistyksen aikana&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="495"/>
        <source>Driver:</source>
        <translation>Ajuri:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="536"/>
        <source>Acceleration method:</source>
        <translation>Kiihdytysmenetelmä:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="557"/>
        <location filename="../../src/settingsdialog.ui" line="589"/>
        <source>Default</source>
        <translation>Oletus</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="562"/>
        <source>Yes</source>
        <translation>Kyllä</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="441"/>
        <location filename="../../src/settingsdialog.ui" line="567"/>
        <source>No</source>
        <translation>Ei</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="430"/>
        <source>PCI reset:</source>
        <translation>PCI nollaus:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="437"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Reset the Nvidia card at the PCI level before reloading the nvidia module&lt;/p&gt;&lt;p&gt;&lt;span style=&quot; font-style:italic;&quot;&gt;No&lt;/span&gt;: does not perform any reset&lt;/p&gt;&lt;p&gt;&lt;span style=&quot; font-style:italic;&quot;&gt;Function level&lt;/span&gt;: perform a light &amp;quot;function-level&amp;quot; reset&lt;/p&gt;&lt;p&gt;&lt;span style=&quot; font-style:italic;&quot;&gt;Hot reset&lt;/span&gt;: perform a &amp;quot;hot reset&amp;quot; of the PCI bridge (this method messes with the hardware directly and will perform a PCI remove even if it disabled, please read the online documentation of Optimus Manager before using it)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Nollaa NVIDIA kortti PCI-tasolla, ennen kuin NVIDIA moduli ladataan uudelleen&lt;/p&gt;&lt;p&gt;&lt;span style=&quot; font-style:italic;&quot;&gt;Ei&lt;/span&gt;: Nollaus toimintoa ei tehdä&lt;/p&gt;&lt;p&gt;&lt;span style=&quot; font-style:italic;&quot;&gt;Toimintotaso&lt;/span&gt;: Suorita kevyt &quot;toimintotason&quot; nollaus&lt;/p&gt;&lt;p&gt;&lt;span style=&quot; font-style:italic;&quot;&gt;Välitön nollaus&lt;/span&gt;: Suorittaa nollauksen suoraan PCI-siltaan (tämä menetelmä ajetaan suoraan laitteistoon ja suorittaa PCI:n poistamisen, vaikka se olisi poistettu käytöstä. Lue Optimus Manager -sovelluksen ohjeet verkossa ennen sen käyttöä)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="446"/>
        <source>Function level</source>
        <translation>Toimintotaso</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="451"/>
        <source>Hot reset</source>
        <translation>Välitön nollaus</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="462"/>
        <source>PCI remove</source>
        <translation>PCI poisto</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="502"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;DRI version&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;DRI versio&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="365"/>
        <source>PCI power control</source>
        <translation>PCI-tehon säätö</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="362"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Enable PCI power management in Intel mode&lt;/p&gt;&lt;p&gt;This option is incompatible with ACPI call and Bbswitch switching methods, so it will be ignored in those cases&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Ota PCI-virran hallinta käyttöön Intel-tilassa&lt;/p&gt;&lt;p&gt;Tämä vaihtoehto ei ole yhteensopiva ACPI- ja Bbswitch-kytkennän kanssa, joten se ohitetaan niissä jokatapauksessa&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="413"/>
        <source>Switching method:</source>
        <translation>Kytkentä tapa:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="459"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Remove the Nvidia card from the PCI bus&lt;/p&gt;&lt;p&gt;May prevent crashes caused by power switching&lt;/p&gt;&lt;p&gt;Ignored if switching method is Nouveau or Bbswitch&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Nvidia-kortin poistaminen PCI-väylästä&lt;/p&gt;&lt;p&gt;Voi estää virrankytkennän aiheuttamat kaatumiset&lt;/p&gt;&lt;p&gt;Suljettu pois, jos kytkentätapa on Nouveau tai Bbswitch &lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="519"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Driver to use for the Intel GPU&lt;br/&gt;&lt;br/&gt;To use the Intel driver, you need to install the package &amp;quot;xf86-video-intel&amp;quot;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Ohjainta käytetään Intelin GPU:ssa&lt;br/&gt;&lt;br/&gt;Intelin ohjaimen käyttäminen edellyttää pakettien asentamista &amp;quot;xf86-video-intel&amp;quot;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="553"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Enable TearFree option in the Xorg configuration&lt;/p&gt;&lt;p&gt;Only applies to the Intel driver&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Ota TearFree-vaihtoehto käyttöön Xorg kokoonpanossa&lt;/p&gt;&lt;p&gt;Koskee vain Intel-ohjainta&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="585"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Acceleration method (corresponds to AccelMethod in the Xorg configuration)&lt;/p&gt;&lt;p&gt;Only applies to the Intel driver&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Kiihdytysmenetelmä (vastaa AccelMethodia Xorg-kokoonpanossa)&lt;/p&gt;&lt;p&gt;Koskee vain Intel-ohjainta &lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="686"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Enable modesetting&lt;/p&gt;&lt;p&gt;Required for PRIME Synchronization (which prevents tearing)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Käytä moodien säätöä&lt;/p&gt;&lt;p&gt;Tarvitaan PRIME-synkronointiin (joka estää repeytymisen)&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="716"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Enable triple buffering&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Kolminkertainen puskurointi käyttöön&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="719"/>
        <source>Triple buffer</source>
        <translation>Kolminkertainen puskurointi</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="776"/>
        <location filename="../../src/settingsdialog.ui" line="907"/>
        <source>Version:</source>
        <translation>Versio:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="790"/>
        <location filename="../../src/settingsdialog.ui" line="884"/>
        <source>Author:</source>
        <translation>Tekijä:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="797"/>
        <location filename="../../src/settingsdialog.ui" line="921"/>
        <source>License:</source>
        <translation>Lisenssi:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.cpp" line="219"/>
        <source>Select icon</source>
        <translation>Valitse kuvake</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.cpp" line="220"/>
        <source>Images (*.png *.jpg *.bmp);;All files(*)</source>
        <translation>Kuvat (*.png *.jpg *.bmp);;Kaikki tiedostot(*)</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.cpp" line="239"/>
        <source>Unable to find Optimus Manager daemon.</source>
        <translation>Optimus Manager -taustaprosessia ei löydy.</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.cpp" line="240"/>
        <source>Please check the integrity of the package that provides Optimus Manager.</source>
        <translation>Tarkista Optimus Manageria tarjoavan paketin eheys.</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.cpp" line="242"/>
        <source>Not found!</source>
        <translation>Ei löydetty!</translation>
    </message>
</context>
</TS>