<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="es_ES" sourcelanguage="en">
<context>
    <name>AppSettings</name>
    <message>
        <location filename="../../src/appsettings.cpp" line="71"/>
        <source>Unable to create autorun file from &apos;%1&apos;</source>
        <translation>No se puede crear el fichero &apos;autorun&apos; a partir de &apos;%1&apos;</translation>
    </message>
</context>
<context>
    <name>OptimusManager</name>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="51"/>
        <location filename="../../src/optimusmanager.cpp" line="193"/>
        <source>Switch to Intel</source>
        <translation>Cambiar a Intel</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="52"/>
        <location filename="../../src/optimusmanager.cpp" line="194"/>
        <source>Switch to Nvidia</source>
        <translation>Cambiar a Nvidia</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="54"/>
        <location filename="../../src/optimusmanager.cpp" line="195"/>
        <source>Exit</source>
        <translation>Salir</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="62"/>
        <location filename="../../src/optimusmanager.cpp" line="190"/>
        <source>Current videocard: </source>
        <translation>GPU Actual: </translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="171"/>
        <location filename="../../src/optimusmanager.cpp" line="181"/>
        <source>The specified icon &apos;%1&apos; for the current GPU is invalid. The default icon will be used.</source>
        <translation>El icono especificado &apos;%1&apos; para la GPU no es aceptado. Un icono por defecto se usará en su lugar.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="208"/>
        <source>You are about to switch GPU.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="210"/>
        <source>You will be automatically logged out to apply the changes.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="221"/>
        <source>The Optimus Manager service is not running.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="273"/>
        <source>There are %1 other desktop sessions open. The GPU switch will not become effective until you have manually logged out from ALL desktop sessions.
Continue?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="287"/>
        <source>Wayland session found.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="288"/>
        <source>Session %1, started by %2, is a Wayland session. Wayland is not supported by Optimus Manager, so GPU switching may fail.
Continue anyway?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="306"/>
        <source>The Bumblebee service (%1) is running.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="347"/>
        <source>The Xorg driver &apos;%1&apos; is not installed.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="348"/>
        <source>Optimus Manager will use &apos;%1&apos; driver instead. You can change driver in settings or install the &apos;%2&apos; driver from the package &apos;%3&apos;.
Continue anyway?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="365"/>
        <source>Unable to connect to Optimus Manager daemon to switch GPU: %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="321"/>
        <source>If you did not create it yourself, it was likely generated by your distribution or by an Nvidia utility.
This file may contain hard-coded GPU configuration that could interfere with Optimus Manager, so it is recommended that you delete it before proceeding.
Ignore this warning and proceed with GPU switching?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="335"/>
        <source>This file was auto-generated by the Manjaro driver utility (MHWD). This will likely interfere with GPU switching, so Optimus Manager will delete this file automatically if you proceded with GPU switching.
Proceed?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="212"/>
        <source>After applying the settings, you will need to manually re-login to change the video card.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="222"/>
        <source>Please enable and start it with:
&apos;%1&apos;
&apos;%2&apos;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="233"/>
        <location filename="../../src/optimusmanager.cpp" line="247"/>
        <source>The %1 module does not seem to be available for the current kernel.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="234"/>
        <source>Power switching will not work.
You can set &apos;%1&apos; for GPU switching in settings or install bbswitch forthe default kernel with &apos;%2&apos; or for all kernels with &apos;%3&apos;.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="248"/>
        <source>It is likely the Nvidia driver was not properly installed. GPU switching will probably fail, continue anyway?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="258"/>
        <source>Looks like you&apos;re using a non-patched version of the Gnome Display Manager (GDM).</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="259"/>
        <source>GDM need to be patched for Prime switching. Follow &lt;a href=&apos;https://github.com/Askannz/optimus-manager&apos;&gt;this&lt;/a&gt; instructions to install a patched version. Without a patched GDM version, GPU switching will likely fail.
Continue anyway?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="272"/>
        <source>Multiple running sessions detected.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="307"/>
        <source>This can interfere with Optimus Manager. Before attempting a GPU switch, it is recommended that you disable this service with &apos;%1&apos; and reboot your computer.
Ignore this warning and proceed with GPU switching now?</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="320"/>
        <location filename="../../src/optimusmanager.cpp" line="334"/>
        <source>Found a Xorg config file at &apos;%1&apos;.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="374"/>
        <source>Unable to send GPU name to switch to Optimus Manager daemon: %1</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="381"/>
        <source>Configuration successfully applied. Your GPU will be switched after next login.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
<context>
    <name>OptimusSettings</name>
    <message>
        <location filename="../../src/optimussettings.cpp" line="64"/>
        <source>Unable to connect to optimus-manager daemon to send startup mode: </source>
        <translation>No se pudo conectar con el daemon de optimus-manager para enviar el modo de encendido: </translation>
    </message>
    <message>
        <location filename="../../src/optimussettings.cpp" line="70"/>
        <source>Unable to send startup mode to optimus-manager daemon: </source>
        <translation>No se pudo enviar el modo de encendido al daemon de optimus manager: </translation>
    </message>
    <message>
        <location filename="../../src/optimussettings.cpp" line="79"/>
        <source>Unable to open startup mode file</source>
        <translation>No se pudo abrir el fichero de modo de encendido</translation>
    </message>
    <message>
        <location filename="../../src/optimussettings.cpp" line="97"/>
        <source>Unknown mode in startup file</source>
        <translation>Modo desconocido en el fichero de encendido</translation>
    </message>
</context>
<context>
    <name>SettingsDialog</name>
    <message>
        <location filename="../../src/settingsdialog.ui" line="14"/>
        <location filename="../../src/optimusmanager.cpp" line="49"/>
        <location filename="../../src/optimusmanager.cpp" line="192"/>
        <source>Settings</source>
        <translation>Configuración</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="59"/>
        <location filename="../../src/settingsdialog.ui" line="112"/>
        <source>General</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="95"/>
        <source>About</source>
        <translation>Acerca de</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="172"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Application language&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Lenguaje de la aplicación.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="175"/>
        <source>Language:</source>
        <translation>Lenguaje:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="122"/>
        <source>&lt;System language&gt;</source>
        <translation>&lt;Idioma del sistema&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="198"/>
        <source>Launch at startup</source>
        <translation>Lanzar al inicio</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="205"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Show confirmation dialog when switching GPU&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Mostrar mensaje de confirmación al cambiar de GPU.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="208"/>
        <source>Confirm switching</source>
        <translation>Confirmar cambio de GPU</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="245"/>
        <source>Nvidia icon:</source>
        <translation>Icono de Nvidia:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="224"/>
        <source>Intel icon:</source>
        <translation>Icono de Intel:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="327"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Specify which GPU will be used by default when the system boots&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Especificar que GPU será usada por defecto cuando el sistema se reinicie.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="381"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Module used for power switching&lt;/p&gt;&lt;p&gt;If you select &amp;quot;None&amp;quot;, no power switching will be done at all (the Nvidia GPU will stay powered at all times)&lt;/p&gt;&lt;p&gt;If you use bbswitch, you will not be able to use video outputs attached to your Nvidia GPU in Intel mode&lt;/p&gt;&lt;p&gt;To use the bbswitch mode, the bbswitch module must be installed for your current kernel&lt;/p&gt;&lt;p&gt;You can install it for the default kernel with &amp;quot;pacman -S bbswitch&amp;quot;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Modulo usado para la administración de nergía al cambia de GPU.&lt;/p&gt;&lt;p&gt;Si seleccionas &amp;quot;Ninguno&amp;quot;, No se aplicarán cambios en la gestión de energía (La GPU nvidia permanecerá encendida todo el tiempo)&lt;/p&gt;&lt;p&gt;Si utilizas bbswitch , no podrás usar salidas de video asociadas a tu GPU nvidia en modo Intel.&lt;/p&gt;&lt;p&gt;Para utilizar el modo bbswitch, el modulo bbswitch debe estar instalado en tu kernel.&lt;/p&gt;&lt;p&gt;Puedes instalarlo para el kernel predeterminado con &amp;quot;pacman -S bbswitch&amp;quot;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="359"/>
        <source>Nvidia (one boot)</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="371"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Automatically log out the current desktop session when switching GPUs&lt;/p&gt;&lt;p&gt;At the moment this is only supported for Gnome, KDE Plasma and Xfce&lt;/p&gt;&lt;p&gt;If this options is disabled or you use a different desktop environment, GPU switching only becomes effective at the next graphical session login&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="374"/>
        <source>Automatic logout</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="441"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Driver to use for the Intel GPU&lt;br/&gt;&lt;br/&gt;To use the intel driver, you need to install the package &amp;quot;xf86-video-intel&amp;quot;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="585"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;This will be set using the Xsetup script passed to your login manager&lt;br/&gt;It will run the command&lt;/p&gt;&lt;p&gt;xrandr --dpi &amp;lt;dpi value&amp;gt;&lt;/p&gt;&lt;p&gt;Leave 0 for the default&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Será definido utilizando el script Xsetup pasado a tu gestor de inicio de sesión.&lt;br/&gt;Ejecutará el comando&lt;/p&gt;&lt;p&gt;xrandr --dpi &amp;lt;dpi value&amp;gt;&lt;/p&gt;&lt;p&gt;Deja 0 para usar el valor por defecto.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="618"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Whether or not to enable the NVreg_UsePageAttributeTable option in the Nvidia driver &lt;span style=&quot; font-style:italic;&quot;&gt;Recommended&lt;/span&gt;, can cause poor CPU performance otherwise&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Activar, o no, la opción NVreg_UsePageAttributeTable en el driver Nvidia.&lt;span style=&quot; font-style:italic;&quot;&gt;Recomendado&lt;/span&gt;, de lo contrario puede causar bajo rendimiento de CPU.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="631"/>
        <source>Overclocking options</source>
        <translation>Opciones de overclocking</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="384"/>
        <source>Switching backend:</source>
        <translation>Cambio de backend:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="195"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;~/.config/autostart will be used&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;~/.config/autostart será utilizado.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="218"/>
        <source>Tray icons</source>
        <translation>Icono de bandeja</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="252"/>
        <location filename="../../src/settingsdialog.ui" line="259"/>
        <source>Choose icon</source>
        <translation>Elegir icono</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="330"/>
        <source>Startup mode:</source>
        <translation>Modo de inicio:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="296"/>
        <source>None</source>
        <translation>Ninguno</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="118"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Interface language&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="231"/>
        <location filename="../../src/settingsdialog.ui" line="238"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Path to the icon or icon name from theme&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="292"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Backend to be used for switching GPU&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="337"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;GPU that will be used during normal system startup&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="417"/>
        <source>Driver:</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="507"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Enable AccelMethod option in the Xorg configuration&lt;br/&gt;&lt;br/&gt;This option compatible only with the Intel driver and will be ignored if it is not selected&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Activa la opción &apos;AccelMethod&apos; en la configuración de Xorg.&lt;br/&gt;&lt;br/&gt;Esta opción solo es compatible con el driver Intel y será ignorada si no esta seleccionado.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="458"/>
        <source>Acceleration method:</source>
        <translation>Método de aceleración:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="479"/>
        <location filename="../../src/settingsdialog.ui" line="511"/>
        <source>Default</source>
        <translation>Predeterminado</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="475"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Enable TearFree option in the Xorg configuration&lt;br/&gt;&lt;br/&gt;This option compatible only with the Intel driver and will be ignored if it is not selected&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Activa la opción &apos;TearFree&apos; en la configuración de Xorg.&lt;br/&gt;&lt;br/&gt;Esta opción solo es compatible con el driver Intel y será ignorada si no esta seleccionado.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="484"/>
        <source>Yes</source>
        <translation>Si</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="489"/>
        <source>No</source>
        <translation></translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="424"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;DRI version&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Versión DRI&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="542"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Whether or not to enable modesetting for the nouveau driver&lt;/p&gt;&lt;p&gt;Does not affect modesetting for the Intel GPU driver&lt;/p&gt;&lt;p&gt;This option is incompatible with bbswitch and will be ignored if it is enabled&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Activar, o no, modsetting para el driver nouveu.&lt;/p&gt;&lt;p&gt;No afecta a modsetting para el driver GPU Intel.&lt;/p&gt;&lt;p&gt;Esta opción es incompatible con bbswitch y será ignorada está activado.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="608"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Whether or not to enable modesetting&lt;/p&gt;&lt;p&gt;Required for PRIME Synchronization&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Activar, o no,  modesetting.&lt;/p&gt;&lt;p&gt;Requerido para sincronización PRIME.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="628"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Enable CoolBits in the Xorg configuration and unlock clocking options in the Nvidia control panel&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Activar cool bits en la configuración de Xorg y desbloquear las opciones de overclocking del panel de control de Nvidia.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="638"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Enable triple buffering&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Activar triple buffer&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="641"/>
        <source>Triple buffer</source>
        <translation>Triple buffer</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="698"/>
        <location filename="../../src/settingsdialog.ui" line="829"/>
        <source>Version:</source>
        <translation>Versión:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="712"/>
        <location filename="../../src/settingsdialog.ui" line="806"/>
        <source>Autor:</source>
        <translation>Autor:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="719"/>
        <location filename="../../src/settingsdialog.ui" line="843"/>
        <source>License:</source>
        <translation>Licencia:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.cpp" line="201"/>
        <source>Select icon</source>
        <translation>Seleccionar icono</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.cpp" line="202"/>
        <source>Images (*.png *.jpg *.bmp);;All files(*)</source>
        <translation>Imágenes (*.png *.jpg *.bmp);;Todos los formatos(*)</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.cpp" line="221"/>
        <source>Unable to find Optimus Manager daemon.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.cpp" line="222"/>
        <source>Please check the integrity of the package that provides Optimus Manager.</source>
        <translation type="unfinished"></translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.cpp" line="224"/>
        <source>Not found!</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
