<?xml version="1.0" ?><!DOCTYPE TS><TS language="tr" version="2.1">
<context>
    <name>AppSettings</name>
    <message>
        <location filename="../../src/appsettings.cpp" line="71"/>
        <source>Unable to create autorun file from &apos;%1&apos;</source>
        <translation>&apos;% 1&apos; den otomatik çalıştırma dosyası oluşturulamıyor</translation>
    </message>
</context>
<context>
    <name>OptimusManager</name>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="55"/>
        <location filename="../../src/optimusmanager.cpp" line="174"/>
        <source>Switch to Intel</source>
        <translation>Intel&apos;e Geç</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="56"/>
        <location filename="../../src/optimusmanager.cpp" line="175"/>
        <source>Switch to Nvidia</source>
        <translation>Nvidia&apos;ya Geç</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="58"/>
        <location filename="../../src/optimusmanager.cpp" line="176"/>
        <source>Exit</source>
        <translation>Çıkış</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="152"/>
        <location filename="../../src/optimusmanager.cpp" line="162"/>
        <source>The specified icon &apos;%1&apos; for the current GPU is invalid. The default icon will be used.</source>
        <translation>Geçerli GPU için belirtilen &apos;%1 &apos; simgesi geçersiz. Varsayılan simge kullanılacaktır.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="189"/>
        <source>You are about to switch GPU.</source>
        <translation>GPU’yu değiştirmek üzeresiniz.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="191"/>
        <source>You will be automatically logged out to apply the changes.</source>
        <translation>Değişiklikleri uygulamak için otomatik olarak oturumunuz kapatılacaktır.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="202"/>
        <source>The Optimus Manager service is not running.</source>
        <translation>Optimus Manager hizmeti çalışmıyor.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="251"/>
        <source>There are %1 other desktop sessions open. The GPU switch will not become effective until you have manually logged out from ALL desktop sessions.
Continue?</source>
        <translation>%1 diğer masaüstü oturumları açık. Tüm masaüstü oturumlarından elle çıkana kadar GPU etkili olmaz.
Devam edilsin mi?</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="265"/>
        <source>Wayland session found.</source>
        <translation>Wayland oturumu bulundu.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="266"/>
        <source>Session %1, started by %2, is a Wayland session. Wayland is not supported by Optimus Manager, so GPU switching may fail.
Continue anyway?</source>
        <translation>% 1 oturumu,% 2 tarafından başlatılan bir Wayland oturumu. Wayland, Optimus Manager tarafından desteklenmiyor, bu nedenle GPU değişimi başarısız olabilir.
Devam edilsin mi?</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="283"/>
        <source>The Bumblebee service (%1) is running.</source>
        <translation>Bumblebee servisi (% 1) çalışıyor.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="324"/>
        <source>The Xorg driver &apos;%1&apos; is not installed.</source>
        <translation>Xorg sürücüsü &apos;%1&apos; yüklü değil.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="325"/>
        <source>Optimus Manager will use '%1' driver instead. You can change driver in settings or install the '%2' driver from the package '%3'.
Continue anyway?</source>
        <translation>Optimus Manager bunun yerine &apos;% 1&apos; sürücüsünü kullanacak. Ayarları değiştirerek sürücüyü değiştirebilir veya &apos;% 2&apos; sürücüsünü &apos;% 3&apos; paketinden yükleyebilirsiniz.
Devam edilsin mi?</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="340"/>
        <source>Unable to connect to Optimus Manager daemon to switch GPU: %1</source>
        <translation>GPU’yu değiştirmek için Optimus Manager arkaplana bağlanamıyor:% 1</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="298"/>
        <source>If you did not create it yourself, it was likely generated by your distribution or by an Nvidia utility.
This file may contain hard-coded GPU configuration that could interfere with Optimus Manager, so it is recommended that you delete it before proceeding.
Ignore this warning and proceed with GPU switching?</source>
        <translation>Kendiniz yaratmadıysanız, büyük olasılıkla dağıtımınız veya bir Nvidia hizmet programı tarafından oluşturulmuştur.
Bu dosya Optimus Manager ile etkileşime girebilecek kodlanmış GPU yapılandırması içerebilir, bu yüzden devam etmeden önce silmeniz önerilir.
Bu uyarıyı dikkate almayın ve GPU geçişi ile devam edin.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="312"/>
        <source>This file was auto-generated by the Manjaro driver utility (MHWD). This will likely interfere with GPU switching, so Optimus Manager will delete this file automatically if you proceded with GPU switching.
Proceed?</source>
        <translation>Bu dosya manjaro sürücü yardımcı programı (MHWD) tarafından otomatik olarak oluşturuldu. Bu muhtemelen GPU geçişine müdahale edecektir, bu nedenle GPU geçişine devam ederseniz Optimus Manager bu dosyayı otomatik olarak silecektir.
Devam edilsin mi?</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="193"/>
        <source>After applying the settings, you will need to manually re-login to change the video card.</source>
        <translation>Ayarları uyguladıktan sonra, ekran kartını değiştirmek için elle yeniden giriş yapmanız gerekecektir.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="66"/>
        <location filename="../../src/optimusmanager.cpp" line="171"/>
        <source>Current videocard: %1</source>
        <translation>Mevcut ekran kartı:%1</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="203"/>
        <source>Please enable and start it with:
'%1'
&apos;%2&apos;</source>
        <translation>Lütfen etkinleştirin ve başlatın:
&apos;%1&apos;
&apos;%2&apos;</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="213"/>
        <location filename="../../src/optimusmanager.cpp" line="225"/>
        <source>The %1 module does not seem to be available for the current kernel.</source>
        <translation>% 1 modülü geçerli çekirdek için uygun görünmüyor.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="214"/>
        <source>Power switching will not work.
You can set &apos;%1&apos; for GPU switching in settings or install bbswitch forthe default kernel with &apos;%2&apos; or for all kernels with &apos;%3&apos;.</source>
        <translation>Güç değiştirme çalışmaz.
Ayarlarda GPU geçişi için &apos;% 1&apos; değerini ayarlayabilir veya &apos;% 2&apos; ile varsayılan çekirdek için veya &apos;% 3&apos; olan tüm çekirdekler için bbswitch&apos;i kurabilirsiniz.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="226"/>
        <source>It is likely the Nvidia driver was not properly installed. GPU switching will probably fail, continue anyway?</source>
        <translation>Nvidia sürücüsünün doğru bir şekilde kurulmamış olması muhtemeldir. GPU değişimi muhtemelen başarısız olacak, yine de devam edecek misiniz?</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="236"/>
        <source>Looks like you&apos;re using a non-patched version of the Gnome Display Manager (GDM).</source>
        <translation>Gnome Ekran Yöneticisi&apos;nin (GDM) yamalı olmayan bir sürümünü kullanıyor gibi görünüyor.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="237"/>
        <source>GDM need to be patched for Prime switching. Follow &lt;a href='https://github.com/Askannz/optimus-manager'&gt;this&lt;/a&gt; instructions to install a patched version. Without a patched GDM version, GPU switching will likely fail.
Continue anyway?</source>
        <translation>Prime değiştirme için GDM&apos;nin yamalanması gerekir. Yamalı bir sürüm yüklemek için &lt;a href=&apos;https://github.com/Askannz/optimus-manager&apos;&gt;bu&lt;/a&gt; talimatları izleyin. Yamalanmış bir GDM sürümü olmadan, GPU geçişi büyük olasılıkla başarısız olacaktır.
Devam edilsin mi?</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="250"/>
        <source>Multiple running sessions detected.</source>
        <translation>Çoklu oturumlar tespit edildi.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="284"/>
        <source>This can interfere with Optimus Manager. Before attempting a GPU switch, it is recommended that you disable this service with '%1' and reboot your computer.
Ignore this warning and proceed with GPU switching now?</source>
        <translation>Bu, Optimus Manager ile etkileşime girebilir. Bir GPU değişimini denemeden önce, bu hizmeti &apos;% 1&apos; ile devre dışı bırakmanız ve bilgisayarınızı yeniden başlatmanız önerilir. 
Bu uyarıyı dikkate almayın ve şimdi GPU geçişi ile devam edin.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="297"/>
        <location filename="../../src/optimusmanager.cpp" line="311"/>
        <source>Found a Xorg config file at &apos;%1&apos;.</source>
        <translation>&apos;%1 &apos; de bir Xorg yapılandırma dosyası bulundu.</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="349"/>
        <source>Unable to send GPU name to switch to Optimus Manager daemon: %1</source>
        <translation>Optimus Manager arkaplana geçmek için GPU adı gönderilemiyor:% 1</translation>
    </message>
    <message>
        <location filename="../../src/optimusmanager.cpp" line="356"/>
        <source>Configuration successfully applied. Your GPU will be switched after next login.</source>
        <translation>Yapılandırma başarıyla uygulandı. GPU&apos;nuz bir sonraki oturumu açtıktan sonra değiştirilecektir.</translation>
    </message>
</context>
<context>
    <name>OptimusSettings</name>
    <message>
        <location filename="../../src/optimussettings.cpp" line="61"/>
        <source>Unable to connect to optimus-manager daemon to send startup mode: %1</source>
        <translation>Başlangıç ​​modunu göndermek için optimus-manager arka planına bağlanılamıyor: %1</translation>
    </message>
    <message>
        <location filename="../../src/optimussettings.cpp" line="69"/>
        <source>Unable to send startup mode to optimus-manager daemon: %1</source>
        <translation>Optimus-manager arkaplan programına başlangıç ​​modu gönderilemiyor: %1</translation>
    </message>
    <message>
        <location filename="../../src/optimussettings.cpp" line="79"/>
        <source>Unable to open startup mode file</source>
        <translation>Başlangıç modu dosyası açılamıyor</translation>
    </message>
    <message>
        <location filename="../../src/optimussettings.cpp" line="97"/>
        <source>Unknown mode in startup file</source>
        <translation>Başlangıç dosyasında bilinmeyen mod</translation>
    </message>
</context>
<context>
    <name>SettingsDialog</name>
    <message>
        <location filename="../../src/settingsdialog.ui" line="14"/>
        <location filename="../../src/optimusmanager.cpp" line="53"/>
        <location filename="../../src/optimusmanager.cpp" line="173"/>
        <source>Settings</source>
        <translation>Ayarlar</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="59"/>
        <location filename="../../src/settingsdialog.ui" line="112"/>
        <source>General</source>
        <translation>Genel</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="95"/>
        <source>About</source>
        <translation>Hakkında</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="199"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Application language&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Uygulama dili&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="202"/>
        <source>Language:</source>
        <translation>Dil:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="122"/>
        <source>&lt;System language&gt;</source>
        <translation>&lt;System language&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="225"/>
        <source>Launch at startup</source>
        <translation>Başlangıçta başlat</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="232"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Show confirmation dialog when switching GPU&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;GPU’yu değiştirirken onay iletişim kutusunu göster&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="235"/>
        <source>Confirm switching</source>
        <translation>Geçişi Onayla</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="272"/>
        <source>Nvidia icon:</source>
        <translation>Nvidia simgesi:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="251"/>
        <source>Intel icon:</source>
        <translation>Intel simgesi:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="354"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Specify which GPU will be used by default when the system boots&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Sistem önyüklenirken hangi GPU&apos;nun varsayılan olarak kullanılacağını belirtin&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="408"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Module used for power switching&lt;/p&gt;&lt;p&gt;If you select &amp;quot;None&amp;quot;, no power switching will be done at all (the Nvidia GPU will stay powered at all times)&lt;/p&gt;&lt;p&gt;If you use bbswitch, you will not be able to use video outputs attached to your Nvidia GPU in Intel mode&lt;/p&gt;&lt;p&gt;To use the bbswitch mode, the bbswitch module must be installed for your current kernel&lt;/p&gt;&lt;p&gt;You can install it for the default kernel with &amp;quot;pacman -S bbswitch&amp;quot;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Güç değişimi için kullanılan modül&lt;/p&gt;&lt;p&gt;Eğer &amp;quot;yok&amp;quot; seçeneğini seçerseniz, hiçbir güç geçişi yapılmaz (Nvidia GPU her zaman güç kalacak)&lt;/p&gt;&lt;p&gt;Eğer bbswitch kullanıyorsanız, Nvidia GPU’nuza bağlı video çıkışlarını Intel modunda kullanamazsınız.&lt;/p&gt;&lt;p&gt;Bbswitch modunu kullanmak için, geçerli çekirdeğiniz için bbswitch modülünün kurulu olması gerekir.&lt;/p&gt;&lt;p&gt;Varsayılan çekirdek için &amp;quot;pacman-s bbswitch&amp;quot; ile yükleyebilirsiniz;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="386"/>
        <source>Nvidia (one boot)</source>
        <translation>Nvidia (bir önyükleme)</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="401"/>
        <source>Automatic logout</source>
        <translation>Otomatik çıkış</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="468"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Driver to use for the Intel GPU&lt;br/&gt;&lt;br/&gt;To use the intel driver, you need to install the package &amp;quot;xf86-video-intel&amp;quot;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Intel GPU için kullanılacak sürücü&lt;br/&gt;&lt;br/&gt;Intel sürücüsünü kullanmak için &amp;quot;xf86-video-ıntel&amp;quot; paketini yüklemeniz gerekir;&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="612"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;This will be set using the Xsetup script passed to your login manager&lt;br/&gt;It will run the command&lt;/p&gt;&lt;p&gt;xrandr --dpi &amp;lt;dpi value&amp;gt;&lt;/p&gt;&lt;p&gt;Leave 0 for the default&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Bu, oturum açma yöneticinize iletilen Xsetup komut dosyası kullanılarak ayarlanır.&lt;br/&gt;Komutu çalıştırır&lt;/p&gt;&lt;p&gt;xrandr --dpi &amp;lt;dpi value&amp;gt;&lt;/p&gt;&lt;p&gt;Varsayılan değer için 0 bırakın&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="645"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Whether or not to enable the NVreg_UsePageAttributeTable option in the Nvidia driver &lt;span style=&quot; font-style:italic;&quot;&gt;Recommended&lt;/span&gt;, can cause poor CPU performance otherwise&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Nvidia sürücüsündeki NVreg_UsePageAttributeTable seçeneğinin etkinleştirilip etkinleştirilmeyeceği&lt;span style=&quot; font-style:italic;&quot;&gt;Tavsiye &lt;/span&gt;, aksi takdirde düşük CPU performansına neden olabilir.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="658"/>
        <source>Overclocking options</source>
        <translation>Hızaşırtma seçenekleri</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="411"/>
        <source>Switching backend:</source>
        <translation>Arka uç geçişi:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="222"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;~/.config/autostart will be used&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;~/.config/autostart kullanılacak&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="245"/>
        <source>Tray icons</source>
        <translation>Tepsi simgeleri</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="279"/>
        <location filename="../../src/settingsdialog.ui" line="286"/>
        <source>Choose icon</source>
        <translation>Simge seçin</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="357"/>
        <source>Startup mode:</source>
        <translation>Başlangıç modu:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="323"/>
        <source>None</source>
        <translation>Hiçbiri</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="118"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Interface language&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Arayüz dili&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="258"/>
        <location filename="../../src/settingsdialog.ui" line="265"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Path to the icon or icon name from theme&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Temadan simge veya simge adına giden yol&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="319"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Backend to be used for switching GPU&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;GPU&apos;yu değiştirmek için kullanılacak arka uç&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="364"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;GPU that will be used during normal system startup&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Normal sistem başlatma sırasında kullanılacak olan GPU&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="398"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Automatically log out the current desktop session when switching GPUs&lt;/p&gt;&lt;p&gt;At the moment this is only supported for Gnome, KDE Plasma, Deepin, Xfce, i3, Sway and Openbox&lt;/p&gt;&lt;p&gt;If this options is disabled or you use a different desktop environment, GPU switching only becomes effective at the next graphical session login&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;GPU&apos;ları değiştirirken mevcut masaüstü oturumunu otomatik olarak kapat.&lt;/p&gt;&lt;p&gt;Şu anda bu sadece Gnome, KDE Plazma, Deepin, Xfce, i3, Sway ve Openbox için desteklenmektedir.&lt;/p&gt;&lt;p&gt;Bu seçenekler devre dışı bırakılırsa veya farklı bir masaüstü ortamı kullanıyorsanız, GPU geçişi yalnızca bir sonraki grafik oturumunda etkinleşir.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="444"/>
        <source>Driver:</source>
        <translation>Sürücü:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="534"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Enable AccelMethod option in the Xorg configuration&lt;br/&gt;&lt;br/&gt;This option compatible only with the Intel driver and will be ignored if it is not selected&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Xorg yapılandırmasında AccelMethod seçeneğini etkinleştirin.&lt;br/&gt;&lt;br/&gt;Bu seçenek yalnızca Intel sürücüsü ile uyumludur ve seçili değilse göz ardı edilir.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="485"/>
        <source>Acceleration method:</source>
        <translation>Hızlanma yöntemi:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="506"/>
        <location filename="../../src/settingsdialog.ui" line="538"/>
        <source>Default</source>
        <translation>Varsayılan</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="502"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Enable TearFree option in the Xorg configuration&lt;br/&gt;&lt;br/&gt;This option compatible only with the Intel driver and will be ignored if it is not selected&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Xorg yapılandırmasında TearFree seçeneğini etkinleştirin.&lt;br/&gt;&lt;br/&gt;Bu seçenek yalnızca Intel sürücüsü ile uyumludur ve seçili değilse göz ardı edilir.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="511"/>
        <source>Yes</source>
        <translation>Evet</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="516"/>
        <source>No</source>
        <translation>Hayır</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="451"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;DRI version&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;DRI versiyonu&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="569"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Whether or not to enable modesetting for the nouveau driver&lt;/p&gt;&lt;p&gt;Does not affect modesetting for the Intel GPU driver&lt;/p&gt;&lt;p&gt;This option is incompatible with bbswitch and will be ignored if it is enabled&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Nouveau sürücüsü için mod ayarının etkinleştirilip etkinleştirilmeyeceği&lt;/p&gt;&lt;p&gt;Intel GPU sürücüsü için ayar modunu etkilemez&lt;/p&gt;&lt;p&gt;Bu seçenek bbswitch ile uyumlu değildir ve etkinleştirilmişse göz ardı edilir.&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="635"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Whether or not to enable modesetting&lt;/p&gt;&lt;p&gt;Required for PRIME Synchronization&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Mod ayarlarının etkinleştirilip etkinleştirilmeyeceği&lt;/p&gt;&lt;p&gt;PRIME Senkronizasyonu İçin Gerekli&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="655"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Enable CoolBits in the Xorg configuration and unlock clocking options in the Nvidia control panel&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Xorg yapılandırmasında CoolBits&apos;i etkinleştirin ve Nvidia kontrol panelindeki saat seçenekleri kilidini açın&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="665"/>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Enable triple buffering&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;Üçlü arabelleklemeyi etkinleştir&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="668"/>
        <source>Triple buffer</source>
        <translation>Üçlü arabellek</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="725"/>
        <location filename="../../src/settingsdialog.ui" line="856"/>
        <source>Version:</source>
        <translation>Versiyon:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="739"/>
        <location filename="../../src/settingsdialog.ui" line="833"/>
        <source>Author:</source>
        <translation>Yazar:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.ui" line="746"/>
        <location filename="../../src/settingsdialog.ui" line="870"/>
        <source>License:</source>
        <translation>Lisans:</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.cpp" line="206"/>
        <source>Select icon</source>
        <translation>Simge Seç</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.cpp" line="207"/>
        <source>Images (*.png *.jpg *.bmp);;All files(*)</source>
        <translation>Resimler (*.png *.jpg *.bmp);;Tüm dosyalar(*)</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.cpp" line="226"/>
        <source>Unable to find Optimus Manager daemon.</source>
        <translation>Optimus Manager arkaplanı bulunamadı.</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.cpp" line="227"/>
        <source>Please check the integrity of the package that provides Optimus Manager.</source>
        <translation>Lütfen Optimus Manager&apos;ı sağlayan paketin bütünlüğünü kontrol edin.</translation>
    </message>
    <message>
        <location filename="../../src/settingsdialog.cpp" line="229"/>
        <source>Not found!</source>
        <translation>Bulunamadı!</translation>
    </message>
</context>
</TS>